
name: CI

on:
  push:
    branches: [ main ] # to not change this

jobs:

  deploy:
        
    runs-on: tisska

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Add the process name # required if web process
        run: echo "tisska" > nodename.txt

      - name: Run the process
        run: |
          npm i 
          node updateSecrets.js ${{ secrets.PASSWORD }}  ${{ secrets.STRIPE_SECRET_KEY }}
          bash startMe.sh